name: Release

on:
  push:
    tags: ["*.*.*"]

jobs:
  test:
    runs-on: windows-latest
    permissions:
      contents: write
    env:
      DOTNET_NOLOGO: true
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: recursive
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
      - name: Restore dependencies
        run: nuget restore BetterSort.sln
      - name: Build 1.29.1
        run: msbuild /p:Configuration=Release-1.29.1 BetterSort.sln
      - name: Build 1.34.2
        run: msbuild /p:Configuration=Release-1.34.2 BetterSort.sln
      - uses: ncipollo/release-action@v1
        with:
          artifacts: "*/bin/Release-*/zip/*.zip"
