name: Test

on:
  push:
    branches: [stage]
  pull_request:
    branches: [stage, main]

jobs:
  test:
    runs-on: windows-latest
    env:
      DOTNET_NOLOGO: true
    steps:
      - name: Checkout
        uses: actions/checkout@main
        with:
          submodules: recursive
      - name: Setup MSBuild
        uses: microsoft/setup-msbuild@v2
      - name: Setup VSTest Path
        uses: darenm/Setup-VSTest@v1.2
      - name: Restore dependencies
        run: nuget restore BetterSort.sln
      - name: Build 1.29.1
        run: msbuild /p:Configuration=Release-1.29.1 BetterSort.sln
      - name: Build 1.34.2
        run: msbuild /p:Configuration=Release-1.34.2 BetterSort.sln
      - name: Test
        run: vstest.console.exe --testcasefilter:'TestCategory != NoCi' BetterSort.LastPlayed.Test\bin\Release-1.29.1\BetterSort.LastPlayed.Test.dll BetterSort.Accuracy.Test\bin\Release-1.29.1\BetterSort.Accuracy.Test.dll
      - name: Push to main
        if: ${{ github.event_name == 'push' }}
        run: |
          git fetch --unshallow origin $(git branch --show-current) main
          git push origin HEAD:main
